env_name: HalfCheetah-v4
env_task: ""
env_library: gym
async_collection: 1
record_video: 0
normalize_rewards_online: 1
normalize_rewards_online_scale: 5
frame_skip: 1
frames_per_batch: 1024
optim_steps_per_batch: 1024
batch_size: 256
total_frames: 1000000
prb: 0
lr: 3e-4
policy_update_delay: 2
multi_step: 1
n_steps_return: 2
init_random_frames: 25000
activation: relu
gSDE: 0
from_pixels: 0
#collector_devices: [cuda:1,cuda:1,cuda:1,cuda:1]
collector_devices: [cpu] #,cpu,cpu,cpu]
env_per_collector: 1
num_workers: 1
lr_scheduler: ""
value_network_update_interval: 200
record_interval: 10
max_frames_per_traj: -1
weight_decay: 0.0
init_env_steps: 10000
record_frames: 10000
loss_function: l2
batch_transform: 1
buffer_prefetch: 64
norm_stats: 1
loss: double
logger: wandb
