# environment and task
env:
  name: Hopper-v3
  task: ""
  exp_name: "Hopper-DDPG"
  library: gym
  frame_skip: 1
  max_episode_steps: 1000
  seed: 1

# collector
collector:
  total_frames: 1_000_000
  init_random_frames: 25_000
  frames_per_batch: 1000
  max_frames_per_traj: 1000
  init_env_steps: 1000
  reset_at_each_iter: False
  collector_device: cpu
  env_per_collector: 1


# replay buffer
replay_buffer:
  size: 1000000
  prb: 0 # use prioritized experience replay

# optimization
optim:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr: 3e-4
  weight_decay: 0.0
  batch_size: 256
  target_update_polyak: 0.995

# network
network:
  hidden_sizes: [256, 256]
  activation: relu
  device: "cuda:0"
  noise_type: "ou" # ou or gaussian

# logging
logger:
  backend: wandb
  mode: online
  eval_iter: 25000
