# Environment
env_name: HalfCheetah-v3
env_task: ""
exp_name: "HalfCheetah-SAC"
env_library: gym
record_video: 0
total_frames: 1000000
frames_per_batch: 1000
max_frames_per_traj: 1000
frame_skip: 1
seed: 1

# Collection
init_random_frames: 10000
init_env_steps: 1000
async_collection: 1
collector_device: cpu
env_per_collector: 1
num_workers: 1

# Replay Buffer
buffer_size: 1000000

# Optimization
utd_ratio: 1.0
gamma: 0.99
loss_function: smooth_l1
lr: 3e-4
weight_decay: 0.0
lr_scheduler: ""
batch_size: 256
target_update_polyak: 0.995

# Algorithm
prb: 0 # use prioritized experience replay
activation: relu

# Logging
logger: wandb
mode: online
eval_iter: 25000

# Extra
device: "cuda:0"

default_policy_scale: 1.0
scale_lb: 0.1
